export const metadata = {
  title: 'Garderie Les Z\'heureux',
  description: 'Generated by Next.js',
  icons: {
    icon: "/img/logoZrmWhite.png",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}